// Generated by CoffeeScript 1.12.7
(function() {
  require('./init');

  describe('App', function() {
    it('testing run few', function() {
      var app, formatter, logger, pageFactory, pathResource, pathResult, utils;
      pathResource = _path.join(__dirname, 'assets/page1');
      pathResult = _path.join(__dirname, 'output/Markdown');
      _rmdir.sync(pathResult, {
        'rmdirSync': 'rmdirSync'
      }, function(error) {});
      logger = new Logger(Logger.WARNING);
      utils = new Utils(_fs, _path, _ncp, logger);
      formatter = new Formatter(_cheerio, utils, logger);
      pageFactory = new PageFactory(formatter, utils)
      app = new App(_fs, _exec, _path, _mkdirp, utils, formatter, pageFactory, logger);
      return app.convert(pathResource, pathResult);
    });
  });

}).call(this);
