// Generated by CoffeeScript 1.12.7
(function() {
  const shelljs = require('shelljs')

  require('./init');

  describe('Index', function() {
    this.timeout(50 * 1000)

    it('testing run cmd', function() {
      shelljs.exec(`node ../src/index.js`, function (code, stdout, stderr) {
        if (code !== 0) {
          throw new Error(stderr)
        }
        done()
      })
    });
  });

}).call(this);
