// Generated by CoffeeScript 1.12.7
(function() {
  var Bootstrap;

  Bootstrap = (function() {
    var App, Formatter, Logger, PageFactory, Utils, _cheerio, _exec, _fs, _mkdirp, _ncp, _path;

    function Bootstrap() {}

    _fs = require('fs');

    _exec = require('sync-exec');

    _path = require('path');

    _ncp = require('ncp');

    _cheerio = require('cheerio');

    _mkdirp = require('mkdirp');

    Utils = require('./Utils');

    Logger = require('./Logger');

    Formatter = require('./Formatter');

    App = require('./App');

    PageFactory = require('./PageFactory');


    /**
     * @param {string} pathResource Directory with HTML files or one file. Can be nested.
     * @param {string|void} pathResult Directory where MD files will be generated to. Current dir will be used if none given.
     */

    Bootstrap.prototype.run = function(pathResource, pathResult) {
      var app, formatter, logger, pageFactory, utils;
      if (pathResult == null) {
        pathResult = '';
      }
      pathResource = _path.resolve(pathResource);
      pathResult = _path.resolve(pathResult);
      logger = new Logger(Logger.INFO);
      utils = new Utils(_fs, _path, _ncp, logger);
      formatter = new Formatter(_cheerio, utils, logger);
      pageFactory = new PageFactory(formatter, utils);
      app = new App(_fs, _exec, _path, _mkdirp, utils, formatter, pageFactory, logger);
      logger.info('Using source: ' + pathResource);
      logger.info('Using destination: ' + pathResult);
      return app.convert(pathResource, pathResult);
    };

    return Bootstrap;

  })();

  module.exports = Bootstrap;

}).call(this);
